package algorhythm;

public class TestUI extends javax.swing.JFrame {
    
    private TestCntl parentTestCntl = null;

    /**
     * Creates new form TestUI
     */
    
    public TestUI(TestCntl newTestCntl) {
        parentTestCntl = newTestCntl;
        initComponents();
    }
       
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        arraySortButton = new javax.swing.JButton();
        sortALResult = new javax.swing.JTextField();
        arraySortResults = new javax.swing.JTextField();
        setButton = new javax.swing.JButton();
        setSortResult = new javax.swing.JTextField();
        sortALResults = new javax.swing.JButton();
        backButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(240, 300));

        arraySortButton.setText("Array Sort");
        arraySortButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                arraySortButtonActionPerformed(evt);
            }
        });

        sortALResult.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sortALResultActionPerformed(evt);
            }
        });

        arraySortResults.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                arraySortResultsActionPerformed(evt);
            }
        });

        setButton.setText("Set Sort");
        setButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setButtonActionPerformed(evt);
            }
        });

        setSortResult.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setSortResultActionPerformed(evt);
            }
        });

        sortALResults.setText("AL Sort");
        sortALResults.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sortALResultsActionPerformed(evt);
            }
        });

        backButton.setText("Back");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(sortALResults)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(sortALResult, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(setButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                        .addComponent(setSortResult, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(arraySortButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(arraySortResults, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(26, 26, 26))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(backButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sortALResult, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sortALResults))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(arraySortButton)
                    .addComponent(arraySortResults, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(setButton)
                    .addComponent(setSortResult, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 225, Short.MAX_VALUE)
                .addComponent(backButton)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void sortALResultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sortALResultActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sortALResultActionPerformed

    private void arraySortButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_arraySortButtonActionPerformed
        // TODO add your handling code here:
        String timeResults = String.valueOf(parentTestCntl.sortA());
        arraySortResults.setText(timeResults);
        
    }//GEN-LAST:event_arraySortButtonActionPerformed

    private void arraySortResultsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_arraySortResultsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_arraySortResultsActionPerformed

    private void setButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_setButtonActionPerformed
        // TODO add your handling code here:
        String timeResults = String.valueOf(parentTestCntl.sortSet());
        setSortResult.setText(timeResults);
    }//GEN-LAST:event_setButtonActionPerformed

    private void setSortResultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_setSortResultActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_setSortResultActionPerformed

    private void sortALResultsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sortALResultsActionPerformed
        // TODO add your handling code here:
        String timeResults = String.valueOf(parentTestCntl.sortAL());
        sortALResult.setText(timeResults);
    }//GEN-LAST:event_sortALResultsActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        // TODO add your handling code here:
        parentTestCntl.getNavigationCntl();
    }//GEN-LAST:event_backButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton arraySortButton;
    private javax.swing.JTextField arraySortResults;
    private javax.swing.JButton backButton;
    private javax.swing.JButton setButton;
    private javax.swing.JTextField setSortResult;
    private javax.swing.JTextField sortALResult;
    private javax.swing.JButton sortALResults;
    // End of variables declaration//GEN-END:variables
}
